pipeline {
    agent any

    environment {
        JAVA_HOME = '/opt/homebrew/opt/openjdk/libexec/openjdk.jdk/Contents/Home'
        PATH = "/opt/homebrew/opt/openjdk/bin:${env.PATH}"
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/mishaua1/hillel_2026.git'
            }
        }

        stage('Install dependencies') {
            steps {
                sh '''
                    cd homework_31
                    python3 -m venv venv
                    . venv/bin/activate
                    pip install --upgrade pip
                    pip install -r requirements.txt
                '''
            }
        }

        stage('Run tests') {
            steps {
                sh '''
                    cd homework_31
                    . venv/bin/activate
                    DB_PORT=5432 pytest test_db.py -v --alluredir=allure-results
                '''
            }
        }
    }

    post {
        always {
            allure includeProperties: false, results: [[path: 'homework_31/allure-results']]
            mail to: 'm.stakhiv11@gmail.com',
                 subject: "Jenkins: ${currentBuild.fullDisplayName} - ${currentBuild.currentResult}",
                 body: "Пайплайн завершився зі статусом: ${currentBuild.currentResult}\nДеталі: ${env.BUILD_URL}"
        }
    }
}
