pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/mishaua1/hillel_2026.git'
            }
        }

        stage('Install dependencies') {
            steps {
                sh '''
                    cd homework_31
                    python3 -m venv venv
                    . venv/bin/activate
                    pip install --upgrade pip
                    pip install -r requirements.txt
                '''
            }
        }

        stage('Run tests') {
            steps {
                sh '''
                    cd homework_31
                    . venv/bin/activate
                    DB_PORT=5432 pytest test_db.py -v --alluredir=allure-results
                '''
            }
        }
    }

    post {
        always {
            allure includeProperties: false, results: [[path: 'homework_31/allure-results']]
        }
    }
}
